openapi: 3.0.0
info:
  title: 알림 관리 API
  version: 1.0.0
  description: API documentation for managing user notifications
paths:
  /notifications/create:
    post:
      summary: Create a new notification
      description: Creates a notification for a user based on a specific event.
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user receiving the notification.
                  example: 64b3e2c86f4f3e0019f9a789
                type:
                  type: string
                  description: The type of notification.
                  enum: [system, user]
                  example: user
                message:
                  type: string
                  description: The message content of the notification.
                  example: "Your profile has been approved."
      responses:
        '201':
          description: Notification created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Notification ID
                        example: 64b3e2c86f4f3e0019f9a780
                      userId:
                        type: string
                        description: User ID
                        example: 64b3e2c86f4f3e0019f9a789
                      type:
                        type: string
                        example: user
                      message:
                        type: string
                        example: "Your profile has been approved."
                      isRead:
                        type: boolean
                        example: false
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /notifications:
    get:
      summary: Get user notifications
      description: Retrieve all notifications for the authenticated user.
      tags:
        - Notifications
      responses:
        '200':
          description: Successfully retrieved notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 64b3e2c86f4f3e0019f9a780
                        userId:
                          type: string
                          example: 64b3e2c86f4f3e0019f9a789
                        type:
                          type: string
                          example: user
                        message:
                          type: string
                          example: "Your profile has been approved."
                        isRead:
                          type: boolean
                          example: false
                        createdAt:
                          type: string
                          format: date-time
                          example: "2024-12-07T09:00:00.000Z"
                        updatedAt:
                          type: string
                          format: date-time
                          example: "2024-12-07T10:00:00.000Z"
        '500':
          description: Internal server error

  /notifications/{id}/read:
    patch:
      summary: Mark a notification as read
      description: Updates the status of a notification to mark it as read.
      tags:
        - Notifications
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the notification to mark as read.
          example: 64b3e2c86f4f3e0019f9a780
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Notification marked as read.
        '404':
          description: Notification not found
        '500':
          description: Internal server error

  /notifications/{id}:
    delete:
      summary: Delete a notification
      description: Deletes a specific notification by its ID.
      tags:
        - Notifications
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the notification to delete.
          example: 64b3e2c86f4f3e0019f9a780
      responses:
        '200':
          description: Notification deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Notification deleted successfully.
        '404':
          description: Notification not found
        '500':
          description: Internal server error
