openapi: 3.0.0
info:
  title: 알림 관리 API
  version: 1.0.0
  description: 사용자 알림을 관리하기 위한 API 문서
paths:
  /notifications/create:
    post:
      summary: 알림 생성
      description: 특정 이벤트를 기반으로 사용자의 알림을 생성합니다.
      tags:
        - Notifications
      parameters:
        - name: type
          in: query
          schema:
            required: true
            type: string
            description: The type of notification.
            enum: [system, user]
            example: user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user receiving the notification.
                  example: _id...
                type:
                message:
                  type: string
                  description: The message content of the notification.
                  example: "Your Application has been Rejected."
      responses:
        '201':
          description: Notification created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Notification ID
                      userId:
                        type: string
                        description: User ID
                        example: 64b3e2c86f4f3e0019f9a789
                      type:
                        type: string
                        example: user
                      message:
                        type: string
                        example: "Your profile has been approved."
                      isRead:
                        type: boolean
                        example: false
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /notifications:
    get:
      summary: 수신 목록 조회
      description: 사용자의 모든 알림을 조회합니다.
      tags:
        - Notifications
      parameters:
        - name: read
          in: query
          schema:
            type: string
            required: true
            description: The type of recieve.
            enum: 
              - All
              - true
              - false
            example: All
      responses:
        '200':
          description: Successfully retrieved notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 64b3e2c86f4f3e0019f9a780
                        type:
                          type: string
                          example: user
                        message:
                          type: string
                          example: "Your profile has been approved."
                        isRead:
                          type: boolean
                          example: false
                        createdAt:
                          type: string
                          format: date-time
                          example: "2024-12-07T09:00:00.000Z"
        '500':
          description: Internal server error

  /notifications/{id}/read:
    patch:
      summary: 알림을 읽음으로 표시
      description:  알림의 상태를 읽음으로 업데이트합니다.
      tags:
        - Notifications
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the notification to mark as read.
          example: 64b3e2c86f4f3e0019f9a780
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Notification marked as read.
        '404':
          description: Notification not found
        '500':
          description: Internal server error

  /notifications/{id}:
    delete:
      summary: 알림 삭제
      description: 알림을 삭제합니다.
      tags:
        - Notifications
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the notification to delete.
          example: 64b3e2c86f4f3e0019f9a780
      responses:
        '200':
          description: Notification deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Notification deleted successfully.
        '404':
          description: Notification not found
        '500':
          description: Internal server error
